// <auto-generated />
using AppWork.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AppWork.Migrations
{
    [DbContext(typeof(ManagerContext))]
    [Migration("20191015194221_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AppWork.Models.Manager", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProektId");

                    b.Property<int>("ProgramistId");

                    b.HasKey("ID");

                    b.HasIndex("ProektId");

                    b.HasIndex("ProgramistId");

                    b.ToTable("ManageWork");
                });

            modelBuilder.Entity("AppWork.Models.Proekt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("NumberOfWorkers");

                    b.Property<string>("ProjectName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Proekt");
                });

            modelBuilder.Entity("AppWork.Models.Programist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Surname");

                    b.HasKey("Id");

                    b.ToTable("Programist");
                });

            modelBuilder.Entity("AppWork.Models.Manager", b =>
                {
                    b.HasOne("AppWork.Models.Proekt", "Proekt")
                        .WithMany("Managers")
                        .HasForeignKey("ProektId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AppWork.Models.Programist", "Programist")
                        .WithMany("Managers")
                        .HasForeignKey("ProgramistId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
